### ISSUE TITLE
[Bug] Moving the cursor over multiple stacks of items while holding CTRL+Q only drops the first stack

### ISSUE THREAD

**Issue by unilock** [Mrredstone5230/Ctrl-Q#2] opened 2022-08-04 22:47 UTC
Outside of macOS, while in an inventory, holding CTRL+Q and moving the cursor over more than one stack of items will drop those items in sequence.
With Ctrl+Q, this works while in the player inventory (accessed by pressing "E"), but not in any other inventory, such as chests, furnaces, etc.

Steps to reproduce:
1. Enter any non-player inventory
2. Hover over a stack of more than one item
3. Press and hold CTRL+Q
4. The entire stack is dropped
5. While holding CTRL+Q, move the cursor across other stacks of items
6. Nothing happens

The expected behavior would be that the other stacks of items that the cursor moves over are dropped as well.

I'm in the process of opening a similar issue on [Debugify's](https://github.com/isXander/Debugify) tracker, of which also implements a fix for [MC-22882](https://bugs.mojang.com/browse/MC-22882).

Thanks :)

**Comment by SB2DD** [comment] 2022-08-04 23:10
Actually, this isn't a bug from this mod, but rather a whole Minecraft bug, macOS AND Windows. I have tried replicating the behavior in Windows and I couldn't move the cursor and sequentially drop items. My guess is that this may be an actual feature and not a bug as this only occurs on "server-side"/"sharable" inventories (to avoid duplication or rather visual bugs if chest is broken), but I would personnaly consider this as a bug.
 
Nonetheless, I'm still going to try to fix this as I can absolutely imagine situations where doing this could be needed.

**Comment by SB2DD** [comment] 2022-08-05 05:32
I finally got it!!!! Will work on a new release tomorrow, sorry for the wait. (It's a ridiculously easy fix, but it works perfectly!!)

**Comment by SB2DD** [comment] 2022-08-05 06:21
The fix will be included in v1.8. Thank you so much for reporting this!! Now this mod is a bit useful for Windows users lol.

**Closed as completed by SB2DD** 2022-08-05 06:21 UTC
Labels: bug

**Comment by SB2DD** [comment] 2022-08-05 06:23
https://github.com/Mrredstone5230/Ctrl-Q/releases/tag/1.8

**Comment by unilock** [comment] 2022-08-05 11:29
Oh wow, I must have misremembered it working on Windows. Today I learned!
Thanks for implementing it regardless, I'm sure it'll be quite useful :)
